// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using YogaFrameWebAdapter.DapplersJsonTypes;

namespace YogaFrameWebAdapter.DapplersJsonTypes
{

    public class TblDappler
    {

        [JsonProperty("idtbl_Dapplers")]
        public string IdtblDapplers { get; set; }

        [JsonProperty("idtblParentTable")]
        public string IdtblParentTable { get; set; }

        [JsonProperty("coltblParentTableName")]
        public string ColtblParentTableName { get; set; }

        [JsonProperty("idtblDapples")]
        public string IdtblDapples { get; set; }

        [JsonProperty("colDapplerState")]
        public string ColDapplerState { get; set; }

        [JsonProperty("idtbl_Member")]
        public string IdtblMember { get; set; }
    }

}

namespace YogaFrameWebAdapter
{

    public class Dapplers
    {

        [JsonProperty("tbl_Dapplers")]
        public TblDappler[] TblDapplers { get; set; }
    }

}
