// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using YogaFrameWebAdapter.DapplersJsonTypes;

namespace YogaFrameWebAdapter.DapplersJsonTypes
{

    public class TblDappler
    {

        [JsonProperty("IdtblDapplers")]
        public string IdtblDapplers { get; set; }

        [JsonProperty("IdtblParentTable")]
        public string IdtblParentTable { get; set; }

        [JsonProperty("ColtblParentTableName")]
        public string ColtblParentTableName { get; set; }

        [JsonProperty("IdtblDapples")]
        public string IdtblDapples { get; set; }

        [JsonProperty("ColDapplerState")]
        public string ColDapplerState { get; set; }

        [JsonProperty("IdtblMember")]
        public string IdtblMember { get; set; }
    }

}

namespace YogaFrameWebAdapter
{

    public class Dapplers
    {

        [JsonProperty("TblDapplers")]
        public TblDappler[] TblDapplers { get; set; }
    }

}
