// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using YogaFrameWebAdapter.InputSequencesJsonTypes;

namespace YogaFrameWebAdapter.InputSequencesJsonTypes
{

    public class TblInputSequence
    {

        [JsonProperty("IdtblInputSequences")]
        public string IdtblInputSequences { get; set; }

        [JsonProperty("IdtblMoves")]
        public string IdtblMoves { get; set; }

        [JsonProperty("IdtblDapplers")]
        public string IdtblDapplers { get; set; }
    }

}

namespace YogaFrameWebAdapter
{

    public class InputSequences
    {

        [JsonProperty("TblInputSequences")]
        public TblInputSequence[] TblInputSequences { get; set; }
    }

}
