// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using YogaFrameWebAdapter.JSessionJsonTypes;

namespace YogaFrameWebAdapter.JSessionJsonTypes
{
    public class JSession
    {
        [JsonProperty("dispatch")]
        public Dispatch Dispatch { get; set; }

        [JsonProperty("members")]
        public Members Members { get; set; }

        [JsonProperty("sessions")]
        public Sessions Sessions { get; set; }
    }
}
