// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using JSonPayload.JSessionJsonTypes;

namespace JSonPayload.JSessionJsonTypes
{

    public class Dispatch
    {

        [JsonProperty("Message")]
        public string Message { get; set; }
    }

    public class TblMember
    {

        [JsonProperty("IdtblMembers")]
        public object IdtblMembers { get; set; }

        [JsonProperty("ColNameAlias")]
        public string ColNameAlias { get; set; }

        [JsonProperty("ColNameFirst")]
        public string ColNameFirst { get; set; }

        [JsonProperty("ColNameLast")]
        public string ColNameLast { get; set; }

        [JsonProperty("ColEmailAddress")]
        public string ColEmailAddress { get; set; }

        [JsonProperty("ColPasswordSaltHash")]
        public object ColPasswordSaltHash { get; set; }

        [JsonProperty("ColBio")]
        public object ColBio { get; set; }
    }

    public class Members
    {

        [JsonProperty("TblMembers")]
        public TblMember[] TblMembers { get; set; }
    }

    public class TblSession
    {

        [JsonProperty("IdtblSessions")]
        public object IdtblSessions { get; set; }

        [JsonProperty("GuidSession")]
        public string GuidSession { get; set; }

        [JsonProperty("IdtblMembers")]
        public string IdtblMembers { get; set; }

        [JsonProperty("DtLastHeartBeat")]
        public string DtLastHeartBeat { get; set; }
    }

    public class Sessions
    {

        [JsonProperty("TblSessions")]
        public TblSession[] TblSessions { get; set; }
    }

}

namespace JSonPayload
{

    public class JSession
    {

        [JsonProperty("Dispatch")]
        public Dispatch Dispatch { get; set; }

        [JsonProperty("Members")]
        public Members Members { get; set; }

        [JsonProperty("Sessions")]
        public Sessions Sessions { get; set; }
    }

}
