// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using YogaFrameWebAdapter.MembersJsonTypes;

namespace YogaFrameWebAdapter.MembersJsonTypes
{

    public class TblMember
    {

        [JsonProperty("idtbl_Members")]
        public string IdtblMembers { get; set; }

        [JsonProperty("colNameAlias")]
        public string ColNameAlias { get; set; }

        [JsonProperty("colNameFirst")]
        public string ColNameFirst { get; set; }

        [JsonProperty("colNameLast")]
        public string ColNameLast { get; set; }

        [JsonProperty("colEmailAddress")]
        public string ColEmailAddress { get; set; }

        [JsonProperty("colPasswordSaltHash")]
        public string ColPasswordSaltHash { get; set; }

        [JsonProperty("colBio")]
        public string ColBio { get; set; }
    }

}

namespace YogaFrameWebAdapter
{

    public class Members
    {
        [JsonProperty("dispatch")]
        public Dispatch Dispatch { get; set; }

        [JsonProperty("tbl_Members")]
        public TblMember[] TblMembers { get; set; }
    }

}
