// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using YogaFrameWebAdapter.MovesJsonTypes;

namespace YogaFrameWebAdapter.MovesJsonTypes
{

    public class TblMove
    {

        [JsonProperty("IdtblMoves")]
        public string IdtblMoves { get; set; }

        [JsonProperty("ColName")]
        public string ColName { get; set; }

        [JsonProperty("IdtblCharacters")]
        public string IdtblCharacters { get; set; }

        [JsonProperty("IdtblDapplers")]
        public string IdtblDapplers { get; set; }
    }

}

namespace YogaFrameWebAdapter
{

    public class Moves
    {

        [JsonProperty("TblMoves")]
        public TblMove[] TblMoves { get; set; }
    }

}
