// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using YogaFrameWebAdapter.PulsesJsonTypes;

namespace YogaFrameWebAdapter.PulsesJsonTypes
{

    public class TblPulse
    {

        [JsonProperty("IdtblPulses")]
        public string IdtblPulses { get; set; }

        [JsonProperty("ColDescription")]
        public string ColDescription { get; set; }

        [JsonProperty("IdtblDapplers")]
        public string IdtblDapplers { get; set; }
    }

}

namespace YogaFrameWebAdapter
{

    public class Pulses
    {

        [JsonProperty("TblPulses")]
        public TblPulse[] TblPulses { get; set; }
    }

}
