// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using YogaFrameWebAdapter.SessionsJsonTypes;

namespace YogaFrameWebAdapter.SessionsJsonTypes
{

    public class TblSession
    {

        [JsonProperty("IdtblSessions")]
        public string IdtblSessions { get; set; }

        [JsonProperty("GuidSession")]
        public string GuidSession { get; set; }

        [JsonProperty("IdtblMembers")]
        public string IdtblMembers { get; set; }

        [JsonProperty("DtLastHeartBeat")]
        public string DtLastHeartBeat { get; set; }
    }

}

namespace YogaFrameWebAdapter
{

    public class Sessions
    {
        [JsonProperty("TblSessions")]
        public TblSession[] TblSessions { get; set; }
    }

}
