// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using YogaFrameWebAdapter.TemplateEmailsJsonTypes;

namespace YogaFrameWebAdapter.TemplateEmailsJsonTypes
{

    public class TblTemplateEmail
    {

        [JsonProperty("IdtblTemplateEmails")]
        public string IdtblTemplateEmails { get; set; }

        [JsonProperty("ColSubject")]
        public string ColSubject { get; set; }

        [JsonProperty("ColMessage")]
        public string ColMessage { get; set; }

        [JsonProperty("ColHeaders")]
        public string ColHeaders { get; set; }
    }

}

namespace YogaFrameWebAdapter
{

    public class TemplateEmails
    {

        [JsonProperty("TblTemplateEmails")]
        public TblTemplateEmail[] TblTemplateEmails { get; set; }
    }

}
