//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YogaFrameDeploy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;user=root;database=world;port=3306;password=******;")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.fakeuri.com:21")]
        public string FtpUri {
            get {
                return ((string)(this["FtpUri"]));
            }
            set {
                this["FtpUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fakeusername")]
        public string FtpUserName {
            get {
                return ((string)(this["FtpUserName"]));
            }
            set {
                this["FtpUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fakepassword")]
        public string FtpPassword {
            get {
                return ((string)(this["FtpPassword"]));
            }
            set {
                this["FtpPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"TemplateEmail_VerifyYourAccount_Headers\"")]
        public string TemplateEmail_VerifyYourAccount_Headers {
            get {
                return ((string)(this["TemplateEmail_VerifyYourAccount_Headers"]));
            }
            set {
                this["TemplateEmail_VerifyYourAccount_Headers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Welcome to YogaFrame! Verify your account\"")]
        public string TemplateEmail_VerifyYourAccount_Subject {
            get {
                return ((string)(this["TemplateEmail_VerifyYourAccount_Subject"]));
            }
            set {
                this["TemplateEmail_VerifyYourAccount_Subject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Welcome aboard <username>! Please click the link below to finalize your account." +
            " Once you do, your community voting and content submission privileges will be ac" +
            "tivated: <HyperLinkdForActivation> Have fun, The YogaFrame Staff\"")]
        public string TemplateEmail_VerifyYourAccount_Message {
            get {
                return ((string)(this["TemplateEmail_VerifyYourAccount_Message"]));
            }
            set {
                this["TemplateEmail_VerifyYourAccount_Message"] = value;
            }
        }
    }
}
