// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Example.SampleResponse1JsonTypes;

namespace Example.SampleResponse1JsonTypes
{

    public class TblCharacter
    {

        [JsonProperty("idtbl_Characters")]
        public string IdtblCharacters { get; set; }

        [JsonProperty("colName")]
        public string ColName { get; set; }

        [JsonProperty("colDescription")]
        public string ColDescription { get; set; }
    }

}

namespace Example
{

    public class SampleResponse1
    {

        [JsonProperty("tbl_Characters")]
        public TblCharacter[] TblCharacters { get; set; }
    }

}
